### ISSUE TITLE
Gem issues in Nitrous

### ISSUE THREAD

**Issue by bacitracin** [learn-co-curriculum/Active-Record-Association-Methods#10]
Not sure if this is related to Nitrous or what, but having issues with the gems. 
Just re-forked/cloned the lab, ran bundle install (installing 22 gems), then rake db:migrate, and got 

➜  Active-Record-Association-Methods-v-000 git:(master) ✗ rake db:migrate
Could not find pry-0.10.1 in any of the sources
Run `bundle install` to install missing gems.

Ran bundle update, then rake db:migrate again:
➜  Active-Record-Association-Methods-v-000 git:(master) ✗ rake db:migrate
Could not find activemodel-4.2.6 in any of the sources
Run `bundle install` to install missing gems.

Tried this again, and it's still stuck on activemodel-4.2.6. 

Tried deleting the gemfile.lock and rerunning, but same errors.

I've been trying to do this lab since January, and back then I ran into issues with the migrations not loading in the correct order. It's the same issue seen here: https://github.com/learn-co-curriculum/Active-Record-Association-Methods/issues/5

I took a break and came back to this lab. This gem problem I'm describing didn't start until about a month ago or so.

**Comment by AnnJohn** [comment]
hi @bacitracin sorry about the problem. We'll look into this soon.

**Comment by pletcher** [comment]
Hm, sorry about this. Is the error still happening? Feel free to reopen -- I can't replicate it, though, so I'm closing this for now.
