### ISSUE TITLE
another rake dependency error

### ISSUE THREAD

**Issue by genericlady** [learn-co-curriculum/Active-Record-Association-Methods#11]
what what....  a dependency error with rake?  wuuhhhh.... no way!

**Comment by PeterBell** [comment]
As per https://github.com/learn-co-curriculum/activerecord-associations-intro/issues/11 I _think_ we're good here as long as you're running Ruby 2.x you should have rake as a default gem so I'm going to close this. That said, if you are getting a replicable error not having rake in the Gemfile, please do create another issue and I'll try to replicate. Thanks!
