### ISSUE TITLE
learn-co gem not in gemfile for lab

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/Active-Record-Association-Methods#15]
when running 'learn', was prompted to add "learn-co" gem to gem file. 
// ♥ learn
/Users/BradSmith/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/rubygems_integration.rb:304:in `block in replace_gem': learn-co is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    from /Users/BradSmith/.rvm/gems/ruby-2.2.3/bin/learn:22:in`<main>'
    from /Users/BradSmith/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
    from /Users/BradSmith/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in`<main>'
bash: parse_git_branch: command not found

After adding it, was able to run 'learn', but still got the **following** message: 

// ♥ learn submit
Adding changes...
Committing changes...
Pushing changes to GitHub...
Submitting lesson...
Done.
**bash: parse_git_branch: command not found**
[21:32:45] Active-Record-Association-Methods-v-000

**Comment by pletcher** [comment]
I don't think we want to add `learn-co` to the Gemfile; but the version locking on sinatra-activerecord seems odd. Removing that fixed the issue for me. (I wasn't able to duplicate this issue exactly, but I did run into some other (seemingly related) issues.
