### ISSUE TITLE
Songs spec file needs to create Artist 'Drake'

### ISSUE THREAD

**Issue by gnfisher** [learn-co-curriculum/Active-Record-Association-Methods#16]
The last test fails because no Artist instance is created in the specfile. This can be corrected by adding

`@drake = Artist.create(name: "Drake")`

inside of the `before` statement in `09_song_methods_spec.rb`

**Comment by pletcher** [comment]
Hm, what about using `Artist.find_or_create` in the `Song#drake_made_this` method instead?
