### ISSUE TITLE
Migrations do not run in order when using the Learn IDE

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/Active-Record-Association-Methods#17]
Performed trouble shooting with student. Migrations ran out of order.

**Comment by aturkewi** [comment]
Ref: https://github.com/learn-co-students/Active-Record-Association-Methods-v-000/issues/40

**Comment by deniznida** [comment]
hey, I think the error happens because there are 2 migrate folders. One is under db/migrate the other one is top level.

**Comment by aturkewi** [comment]
I tried removing top level file and migrating and tried removing the one in the db/ dir and migrating. No luck either way when tested on the IDE. Lab runs just fine local mac.
For some reason this seams IDE specific. @loganhasson thoughts?
(Can't copy from IDE right now, so can't paste in full error)

**Comment by aturkewi** [comment]
Logan, please ignore, a student already found the fix and i'll update it today: https://github.com/thegands/Active-Record-Association-Methods-v-000/commit/e424f87439d34988a6ffa9b7f50a6b3c8b5aa64b

**Comment by aturkewi** [comment]
This was a broken deploy. Fixed
