### ISSUE TITLE
Suggested additional test - drake - find_or_create_by_name

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/Active-Record-Association-Methods#18]
for drake_made_this, i would suggest adding a test that fails if the student tries:

  def drake_made_this
    # when this method is called it should assign the song's artist to Drake
    self.artist = Artist.new(name: "Drake")
  end
end

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#23.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hi @jonbf,

Thank you for opening this issue and providing feedback. We've updated the tests in this lesson to test for the presence of a new Artist instance, so this solution will no longer pass the tests.

Thank you for contributin to a Learn lesson!
