### ISSUE TITLE
json 1.8.3 error

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/Active-Record-Association-Methods#21]
when I run rake db:migrate I'm getting an error that json 1.8.3 is not installed 
so I tried to manually "bundle install" as well as a direct "gem install json -v '1.8.3'" 
with no success. in the end I had to run "bundle update" to resolve the situation, so it seems that the preexisting "gemfile.lock" file needs a update.

THANKS

**Comment by curiositypaths** [comment]
Thank you for bringing this to our attention. We updated the lesson's dependencies.

As always thank you for contributing.
