### ISSUE TITLE
Pull request -> lab marked as completed, even if some tests still failing

### ISSUE THREAD

**Issue by wlycdgr** [learn-co-curriculum/Active-Record-Association-Methods#22]
In the middle of working through rspeclementing this lab, I took a moment to create a new branch, committed a suggested improvement to it, and created a pull request for it. After doing this and refreshing the lab page on Learn, the Learn web app marked the lab as completed - even though some of my tests are still failing.

The web app should not mark a lab as completed if the code in the latest pull request submitted by the user isn't passing all the tests, or if not that, then at least it shouldn't mark a lab as completed until student has done at least one run of learn where all tests pass at the same time.

**Comment by wlycdgr** [comment]
(I have no reason to think this issue is specific to this lab, but wasn't sure where else to report it. What is the best way to report issues like this, which are likely to be app-wide?)

**Comment by curiositypaths** [comment]
Hi @wlycdgrfromflatiron,

We included our bug reporting steps below. Thank you for asking.

### Reporting bugs 🐛
If you'd like to [report a bug](http://help.learn.co/improving-learn/reporting-bugs/reporting-a-bug) about the [Learn IDE](http://help.learn.co/the-learn-ide), the [lights not working on Learn](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green), or any other issue with the site, please consult the [Learn Help Center](http://help.learn.co/) and/or escalate the issue via [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson). If you are unable to access Ask a Question or your track is not supported by the Technical Coaches, please send us a message via the [Intercom](https://user-images.githubusercontent.com/17556281/27602126-b825ff3a-5b3f-11e7-9dcd-0ced7e507bfb.png) widget on any [Help Center](http://help.learn.co/) page.
