### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by curiositypaths** [learn-co-curriculum/Active-Record-Association-Methods#23]
PROBLEM: Update to spec suggestion. See issue #18 
NOTIFY: @jonbf

**Comment by drakeltheryuujin** [comment]
PROBLEM: Test for "drake_made_this" #24
NOTIFY: @micahshute

**Comment by maxwellbenton** [comment]
Both issues were related to the final method in this lab and ambiguous tests leading to false passes. Updated this lab's instructions and tests to help clarify expectations for this method and prevent false passes from occuring. Tests now check to see if the method correctly assigns the Artist instance of Drake to a song, and that the Artist instance is either found or created. Messaging points out that Drake does not exist in the DB to begin with and must be created in the method, but not more than once.
