### ISSUE TITLE
Test for "drake_made_this"

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/Active-Record-Association-Methods#24]
Hi, you may want to consider re-writing the test for "drake_made_this" which is the last test for this lab. The instructions never explicitly says to return an artist from the method, but the test requires that an artist with the name of "Drake" is returned. Furthermore, that return value of the method is the only thing being tested, so you can actually pass the test without properly setting the song's artist as long as the method returns an Artist whose name is Drake. I passed the tests using just one line in the last method: Artist.find_or_create_by(name: "Drake"), which clearly doesn't change the song's artist. Thanks!

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #23.
We're closing this issue but invite you to follow #23 .

**Comment by maxwellbenton** [comment]
Hey @micahshute,

We've updated the instructions and tests for this lab so the expectations of this method are clearer while the tests are a bit more strict. This lab will no longer test for the return value, but instead, test to see if the song's artist changes, if an artist record is created for Drake and that only one record is created if the method is run multiple times. This, combined with improved guidance and hints in the material should clear up the confusion this method has caused while also making the solution more specific.
