### ISSUE TITLE
Clarity on last test (drake_made_this)

### ISSUE THREAD

**Issue by georgejeffery** [learn-co-curriculum/Active-Record-Association-Methods#25]
Can it be made explicit that Drake does not exist in the db for this test? Also more clarity on return values would be great, as according to the wording of the test 
``self.artist = Artist.find_by(name: "Drake")``
should work, but I could only get ``self.artist = Artist.find_or_create_by(name: "Drake")`` to pass the test.

Thanks!

**Comment by maxwellbenton** [comment]
HI @georgejeffery,

Thank you for providing this feedback. We've updated this lesson's instructions and tests to specifically point out that Drake does not already exist in the database, which should help prevent this issue from happening with future students.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
