### ISSUE TITLE
id should be 1 and not nil 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/Active-Record-Association-Methods#26]
After rake console, the id returned should be 1 and not nil  

I got a return of id:1 in my terminal by following precisely. I asked AAQ Tech Coach why because I'm trying to understand.   

********
Association Methods
Go ahead and run the test suite and you'll see that we are passing the first 14 tests. Our associations are all working, just because of our migrations and use of macros.

We can now call methods on the objects we associated with one another. Let's play around with our code using the console task we wrote for you in the Rakefile.

rake console
hello = Song.create(name: "Hello")
=> #<Song:0x007fc75a8de3d8 id: nil, name: "Hello", art

**Comment by maxwellbenton** [comment]
Hi @ccklight,

Thank you for spotting this and providing feedback. We've corrected the code snippets in this readme so that they correctly display an id of `1` rather than `nil` and believe this issue is resolved. 

Thanks for contributing to a Learn lesson!
