### ISSUE TITLE
Migration issues

### ISSUE THREAD

**Issue by bacitracin** [learn-co-curriculum/Active-Record-Association-Methods#3]
Just started with "bundle install" and when I run rake db:migrate, getting this: 

➜  Active-Record-Association-Methods-v-000 git:(master) ✗ rake db:migrate
==  CreateGenres: migrating ===================================================
-- create_table(:genres)
   -> 0.0076s
==  CreateGenres: migrated (0.0078s) ==========================================
==  AddGenreToSongs: migrating ================================================
-- add_column(:songs, :genre_id, :integer)
rake aborted!
SQLite3::SQLException: no such table: songs: ALTER TABLE "songs" ADD "genre_id" integer

**Comment by bacitracin** [comment]
Oh, and I'm on Nitrous

**Comment by AnnJohn** [comment]
sorry for the trouble you're having @bacitracin. we'll look into this and try to get it resolved as soon as we can. thanks for raising the issue.

**Comment by aviflombaum** [comment]
For some reason on nitrous the `migrate_db` method used in the migration task I wrote and the test suite doesn't load the files in order. fb1ef325a55c4cbc96bff2e43f93e0cfaf2fa995 fixes it but actually we should just use the rake tasks provided by `sinatra-activerecord` and deprecate rolling our own migration tasks. We'd also have to use `database_cleaner` in the tests which I'm cool with.
