### ISSUE TITLE
having trouble migrating my databse on this lab

### ISSUE THREAD

**Issue by drewvpham** [learn-co-curriculum/Active-Record-Association-Methods#5]
Active-Record-Association-Methods-v-000 git:(master) ✗ rake db:migrate
==  CreateGenres: migrating ===================================================
-- create_table(:genres)
   -> 0.0070s
==  CreateGenres: migrated (0.0072s) ==========================================
==  AddGenreToSongs: migrating ================================================
-- add_column(:songs, :genre_id, :integer)
rake aborted!

**Comment by pletcher** [comment]
Hi @phamducv, thanks for reporting this issue. Can you try deleting the database file (`rm db/playlister-development.db`) and re-running `bundle exec rake db:migrate`? Let me know if you run into further issues.
